### ISSUE TITLE
应该如何将此项目导入Eclipse中

### ISSUE THREAD

**Issue by BLKStone** [fan-wenjie/EasyPR-Java#1]
你好，我是一个Java初学者，也是git初学者，对EasyPR-Java的项目比较感兴趣，想咨询一下该如何将此项目导入到Eclipse中，非常感谢。

**Comment by fan-wenjie** [comment]
此项目是基于INTELLIJ IDEA 的项目。不能直接导入Eclipse。可以把源文件代码和资源拷贝到Eclipse项目中，添加opencv.jar,javacv.jar,javacpp.jar以及对应平台的opencv-(你的操作系统).jar的本机代码库。另外，该项目尚未进行测试。恐怕会有问题

**Comment by blucehu** [comment]
## import static org.bytedeco.javacpp.opencv_core.*;

首先谢谢您的工作；但下载下来 zip 中貌似没有这个包，Main 运行不成功，请提供 bytedeco 包，谢谢！

**Comment by fan-wenjie** [comment]
http://search.maven.org/remotecontent?filepath=org/bytedeco/javacv/0.10/javacv-0.10-bin.zip
git始终无法把jar包上传，所以请从该链接下载。只需把javacv.jar,opencv.jar,javacpp.jar以及对应opencv-操作系统.jar复制进去即可

**Comment by magiccoder12** [comment]
你好，fan-wenjie，我把javacv.jar,opencv.jar,javacpp.jar以及对应opencv-操作系统.jar复制进去之后，执行时出现错误Exception in thread "main" java.lang.NoClassDefFoundError: bin/org/easypr/Main (wrong name: org/easypr/Main)

**Comment by lishaowei0011** [comment]
Plate Detect Test
#

# A fatal error has been detected by the Java Runtime Environment:

#

# EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000007fee8c65704, pid=13504, tid=13536

#

# JRE version: 7.0_25-b17

# Java VM: Java HotSpot(TM) 64-Bit Server VM (23.25-b01 mixed mode windows-amd64 compressed oops)

# Problematic frame:

# C  [opencv_ml2410.dll+0x45704][thread 13576 also had an error]

  CvSVM::predict+0x304
#

# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

#

# An error report file with more information is saved as:

# E:\905\demo\chepaishibie\fan-wenjie-EasyPR-Java-04b31f0\hs_err_pid13504.log

#

# If you would like to submit a bug report, please visit:

# http://bugreport.sun.com/bugreport/crash.jsp

# The crash happened outside the Java Virtual Machine in native code.

# See problematic frame for where to report the bug.

#

[error occurred during error reporting , id 0xc0000005]

**Comment by mumu10** [comment]
我fork了[EasyPR-Java](https://github.com/mumu10/EasyPR-Java)，并完成了v0.1的release，可以支持Eclipse项目，并且原来的项目执行应该是有错的，也做了相应修改。

另外我已经向此仓库提交了pull request，还没有回应，不知道fan-wenjie是否还活跃，如果再过一个月没有回应的话，我会考虑申请fork disconnect 或者重新建个仓库。

**Comment by pz1026** [comment]
根据fan-wenjie提供的包下载后确实可以运行，但是请问我自己在opencv官网现在的包却不能用，请问您的包是在哪里下载的呢？

**Comment by XrazYang** [comment]
您好,刚接触到这个项目,不知道javacv.jar,opencv.jar,javacpp.jar以及对应opencv-操作系统.jar,这四个文件应该复制到对应的什么位置?

**Comment by XrazYang** [comment]
@pz1026  ,您好,您是把那四个包复制到项目的什么位置?能帮忙解答一下吗?谢谢

**Comment by XrazYang** [comment]
@fan-wenjie 您好,从git上下了您的源码,刚开始我直接导入工程,就会显示找不到主类或者无法加载主类的错误,我尝试了一下我的方法,就是新建一个工程,将javacv.jar,opencv.jar,javacpp.jar以及对应opencv-操作系统.jar加入到工程中,然后将src 和res连个文件也拷贝到工程中,就能运行了...谢谢您的源码,对我很有帮助.

**Comment by jefferson163994** [comment]
我添加了除opencv-操作系统.jar这个包，运行后出现Caused by: java.lang.UnsatisfiedLinkError: no msvcp100 in java.library.path这个错误，请问这是什么原因呢？

**Comment by mrhaoqi** [comment]
@mumu10 为什么导入了相应的jar包之后还会出现The method asMat() is undefined for the type opencv_core.MatExpr这样的错误呢？

**Comment by singlenobleJ** [comment]
导入后 Main函数 啥都没有 怎么调试啊

**Comment by ZoeShaw101** [comment]
为什么我导入这四个jar包后，仍然有不能杰解析的类呢？

**Comment by halegreen** [comment]
为什么我导入这四个jar包后，仍然有不能解析的类呢？

**Comment by qvbtxgt** [comment]
根据fan-wenjie提供的链接：http://search.maven.org/remotecontent?filepath=org/bytedeco/javacv/0.10/javacv-0.10-bin.zip
从链接下载jar包，只需把javacv.jar,opencv.jar,javacpp.jar以及对应opencv-操作系统.jar复制进去，另外还需要加上junit.jar包，因为该项目中没有在Main函数中写代码，而是用了junit测试工具，打开src/org.easypr.test，就可以看来里面写的测试代码。

**Comment by zx493952184** [comment]
Class not found org.easypr.test.EasyPrTest
java.lang.ClassNotFoundException: org.easypr.test.EasyPrTest
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:693)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:429)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
我导入了jar包 为什么还有这些错误 小白求解释。。。求大神

**Comment by T5750** [comment]
```
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv</artifactId>
			<version>0.11</version>
			<exclusions>
				<exclusion>
					<groupId>org.bytedeco.javacpp-presets</groupId>
					<artifactId>ffmpeg</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.bytedeco.javacpp-presets</groupId>
					<artifactId>flycapture</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.bytedeco.javacpp-presets</groupId>
					<artifactId>libdc1394</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.bytedeco.javacpp-presets</groupId>
					<artifactId>libfreenect</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.bytedeco.javacpp-presets</groupId>
					<artifactId>videoinput</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.bytedeco.javacpp-presets</groupId>
					<artifactId>artoolkitplus</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.bytedeco.javacpp-presets</groupId>
					<artifactId>flandmark</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
https://github.com/T5750/websites/tree/master/git/easyPR
